### ISSUE TITLE
Problem with compile

### ISSUE THREAD

**Issue by Nikita-Presnov** [filipecalasans/realTimePlot#1]
![изображение](https://user-images.githubusercontent.com/54064458/93016289-c8d6b500-f5c8-11ea-9f53-7e381d3f3e56.png)
This method was introduced in Qt 5.11.
For 5.9 and maybe older replace to data().
![изображение](https://user-images.githubusercontent.com/54064458/93130389-20654580-f6db-11ea-8337-8e979e2dbda8.png)
Change to Qt 5.11 in dependencies.

**Comment by Nikita-Presnov** [comment]
![изображение](https://user-images.githubusercontent.com/54064458/93130185-d9775000-f6da-11ea-9634-943b304267c1.png)
Change to Qt 5.11 in denseness.

**Comment by filipecalasans** [comment]
Thank you @Nikita-Presnov  for pointing that out. I will update the documentation accordingly.

**Comment by filipecalasans** [comment]
Documentation update in: https://github.com/filipecalasans/realTimePlot/commit/0c25e008d7b36db3e2f48256aa316dc1bfd67df9
