### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Nikita-Presnov** [filipecalasans/realTimePlot#2]
Okay, and how can I stop it?
I did not find object Qtimer.
I need to stop image in one moment and set new.

**Comment by filipecalasans** [comment]
Hi @Nikita-Presnov, the rendering period is statically defined and set on a timer using the QObjet API. Usually, we don't want to pause the rendering. Instead, I would recommend interacting with the data stream buffer.

Find below an example using the Qt API to manage the QObject timer. In the example, you will need to store the timer ID returned by the method `startTimer` as a member variable.

```cpp
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow),
    refresh_timer_id(0)
{
    ui->setupUi(this);

    for(int i=0; i<POINT_STREAM_NUM; i++) {
        QSharedPointer<PointStream> stream(new PointStream());
        stream->setSamplesPerSeconds(1000/SAMPLE_GENERATION_PERIOD);
        dataPoints << stream;
        ui->plotArea->addPointStream(stream);
    }

    ui->plotArea->setWindowLengthInSeconds(4.0);

    refresh_timer_id = startRendering();
}


void MainWindow::pauseRendering() {
     killTimer(refresh_timer_id);
     refresh_timer_id = 0;
}


void MainWindow::startRendering() {
     if (refresh_timer_id == 0) {
         refresh_timer_id = startTimer(SAMPLE_GENERATION_PERIOD);
     }
}

```

For more information, please refer to Qt documentation in: https://doc.qt.io/qt-5/qobject.html#startTimer

**Comment by filipecalasans** [comment]
@Nikita-Presnov, I have implemented APIs to allow play/pause the render loop, accompanied by an example on the sample app.

https://github.com/filipecalasans/realTimePlot/pull/3
